# Hindi layout

language_code = "hi"
language_name = "हिन्दी"
language_flag = "🇮🇳"
layout = [
    [
        { text = '1' },
        { text = '2' },
        { text = '3' },
        { text = '4' },
        { text = '5' },
        { text = '6' },
        { text = '7' },
        { text = '8' },
        { text = '9' },
        { text = '0' },
        { action = 'backspace', display_text = 'Backspace', width = 2 },
    ],
    [
        { text = "अ", alternatives = ["ऽ"] },
        { text = 'आ' },
        { text = 'इ' },
        { text = 'ई' },
        { text = 'उ' },
        { text = 'ऊ' },
        { text = 'ऋ', alternatives = ['ऌ'] },
        { text = "ए", alternatives = ["ऍ"] },
        { text = 'ऐ' },
        { text = "ओ", alternatives = ["ऑ", "ॐ"] },
        { text = 'औ' },
        { action = 'enter', display_text = 'Enter', width = 2 },
    ],
    [
        { text = 'क' },
        { text = 'ख' },
        { text = 'ग' },
        { text = 'घ' },
        { text = 'ङ' },
        { text = 'च' },
        { text = 'छ' },
        { text = 'ज' },
        { text = 'झ' },
        { text = 'ञ' },
    ],
    [
        { text = 'ट' },
        { text = 'ठ' },
        { text = 'ड' },
        { text = 'ढ' },
        { text = 'ण' },
        { text = 'त' },
        { text = 'थ' },
        { text = 'द' },
        { text = 'ध' },
        { text = 'न' },
    ],
    [
        { text = "प" },
        { text = "फ" },
        { text = "ब" },
        { text = "भ" },
        { text = "म" },
        { text = "य" },
        { text = "र" },
        { text = "ल", alternatives = ["ळ"] },
        { text = "व" },
        { text = "श" },
        { text = "ष" },
        { text = "स" },
        { text = "ह" },
    ],
    [
        { text = 'ा' },
        { text = 'ि' },
        { text = 'ी' },
        { text = "ु", alternatives = ["ृ"] },
        { text = 'ू' },
        { text = "े", alternatives = ["ॅ"] },
        { text = 'ै' },
        { text = "ो", alternatives = ["ॉ"] },
        { text = 'ौ' },
        { text = "ं", alternatives = ["ँ", "ः"] },
    ],
    [
        { text = "-", alternatives = ["'", "/", "_", "+", "="] },
        { text = "्" },
        { text = "़" },
        { text = "।", alternatives = [".", ",", "?", "!", ":", ";", "॥"] },
        { text = ' ', display_text = 'Space', width = 9 },
        { action = 'language_selector', display_text = 'Lang', width = 2 },
    ],
]
